SCALRCORE-17474 CSB > Set up migration tool (blobtruck) using Terraform
Scalr/terraform-system-blobtruck pull request #1
Opened 2020-12-14 09:17 UTC by brezitskiy

2020-12-15 13:40 UTC, lbn requested changes
Newlines also missing from a few files.

2020-12-15 13:40 UTC, lbn commented on modules/google/variables.tf
> +  default = "f1-micro"
Let's go with n1-standard-2 so that it's not shared.

2020-12-15 13:40 UTC, lbn commented on modules/google/variables.tf
> +  default = "db-f1-micro"
Could use a bigger instance here too by default.

2020-12-15 13:40 UTC, lbn commented on modules/google/variables.tf
> +  default = "131072"
This is in bytes right? Needs to be 134217728.

2020-12-15 13:40 UTC, lbn commented on modules/google/main.tf
> +resource "null_resource" "install_blobtruck_package" {
Could all this be done inside `google_compute_instance.node`?

2020-12-15 13:40 UTC, lbn commented on modules/google/main.tf
> +      "gcloud sql import sql ${google_sql_database_instance.mysql.name} ${local.dump_uri} --database=default --quiet",
Could be done in the instance as well.

2020-12-15 13:40 UTC, lbn commented on modules/google/main.tf
> +      "sudo cp /var/tmp/blobtruck.yml /etc/blobtruck/blobtruck.yml",
Maybe mv to avoid storing credentials in more than one place.

2020-12-15 13:40 UTC, lbn commented on modules/google/main.tf
> +      "sudo curl -s https://${var.packagecloud_token}:@packagecloud.io/install/repositories/scalr/scalr-server-ee-staging/script.rpm.sh | sudo bash",
Need a `packagecloud_repo` variable which is set to `scalr-server-ee` by default.

2020-12-15 13:40 UTC, lbn commented on modules/google/README.md
> +Configures blobtrunk for migrating tf-blob service data from local backend into the Google Cloud Storage
blobtruck.

2020-12-15 13:40 UTC, lbn commented on modules/google/README.md
> +| max_allowed_packet | n/a | `int` | `131072` | no |
Need to clarify that it's in bytes.

2020-12-15 17:53 UTC, emocharnik commented on modules/google/main.tf
> +  instance = google_sql_database_instance.mysql.name
depends on

2020-12-15 17:53 UTC, emocharnik commented on modules/google/main.tf
> +  db_user = "blobtruck"
why this variable is hardcoded?

2020-12-16 10:18 UTC, brezitskiy commented on modules/google/main.tf
> +resource "null_resource" "install_blobtruck_package" {
@lbn looks like it couldn't, there are circular dependencies
`data.template_file.blobtruck_yml` refers to `google_sql_database_instance.mysql` and `google_sql_database_instance.mysql` itself refers to `google_compute_instance.node`

2020-12-16 13:41 UTC, lbn approved these changes

2020-12-21 09:38 UTC, emocharnik approved these changes

2020-12-21 13:16 UTC, merged